package util.hello;

import util.hello.sibling;

/**
 * This code was autogenerated by Skyscraper. DO NOT MODIFY THIS.
 */
public class Dog {

    public String species;

    public String name;

    public int age;

    public Animal sibling;
}
